version: 2
jobs:
  compile:
    docker:
      - image: circleci/openjdk:10.0.1-jdk-node-browsers
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
      - run: ./gradlew --parallel resolveConfigurations
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
      - run: ./gradlew --parallel --stacktrace classes testClasses
      - persist_to_workspace:
          root: .
          paths: [ . ]

  darwin-build-and-run:
    macos:
      xcode: "9.2.0"
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      FL_OUTPUT_DIR: output
      JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
    steps:
      - checkout
      - run: brew upgrade && brew cask install java
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
      - run: ./gradlew doSomething
      - run: ./gradlew tgz
      - run: ./cli/build/mydist/bin/cli
      - store_artifacts:
          path: ./cli/build/distributions/
          destination: darwin-cli
  linux-build-and-run:
    docker:
      - image: circleci/openjdk:10.0.1-jdk-node-browsers
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
      - run: ./gradlew doSomething
      - run: ./gradlew tgz
      - run: ./cli/build/mydist/bin/cli
      - store_artifacts:
          path: ./cli/build/distributions/
          destination: linux-cli
workflows:
  version: 2
  build:
    jobs:
      - compile:
          filters:
            tags:
              only: /.*/
      - linux-build-and-run:
          requires: [ compile ]
          filters:
            tags:
              only: /.*/
      - darwin-build-and-run:
          requires: [ compile ]
          filters:
            tags:
              only: /.*/
